name: Test tendang action
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      tendang:
        image: ghcr.io/kudaliar032/tendang:action-test
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
  action-test:
    runs-on: ubuntu-latest
    services:
      tendang:
        image: ghcr.io/kudaliar032/tendang:action-test
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Run tendang action without value
        uses: ./
        with:
          url: http://localhost:5000
          token: ${{ secrets.TENDANG_TOKEN }}
          name: withoutvalue
      - name: Run tendang action with value
        uses: ./
        with:
          url: http://localhost:5000
          token: ${{ secrets.TENDANG_TOKEN }}
          name: withvalue
          value: hello
