name: Test tendang action
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      tendang:
        image: ghcr.io/kudaliar032/tendang:action-test
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run nodejs test
        run: |
          npm run lint
          npm run test
